name: Build and Push To Docker Registry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: clinicalapp
          registry: crclinicaldev.azurecr.io
          tag_with_ref: true
          tag_with_sha: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

